openapi: 3.0.0
info:
  title: Rudradev's Educase-OA Schl API
  version: 1.0.0
  description: API for managing school data
paths:
  /api/addSchool:
    post:
      summary: Add a new school
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
      responses:
        '201':
          description: School added successfully
        '400':
          description: Bad request
        '500':
          description: Server error
  /api/listSchools:
    get:
      summary: List schools sorted by proximity
      parameters:
        - in: query
          name: latitude
          required: true
          schema:
            type: number
        - in: query
          name: longitude
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '500':
          description: Server error